name: Run CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip --version
      - name: Install library and dependencies
        run: |
          pip install -e ".[dev]"
          black --version
          pytest --version
      - name: Check code formatting
        run: |
          black --check .
      - name: Run tests
        run: |
          pytest
        if: always()
